import Footer from '@/components/layout/Footer/Footer'
import Header from '@/components/layout/Header/Header'
import { Toaster } from '@/components/ui/Sonner/Sonner'
import { CartProvider } from '@/context/CartContext'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const interSans = Inter({
	variable: '--font-inter-sans',
	subsets: ['latin']
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${interSans.variable} antialiased`}>
				<CartProvider>
					<Header />
					{children}
					<Footer />
				</CartProvider>
				<Toaster />
			</body>
		</html>
	)
}
